/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseFileListInfo: typeof import('./src/components/BaseFileListInfo.vue')['default']
    ChangeIndicator: typeof import('./src/components/ChangeIndicator.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    DraggableImage: typeof import('./src/components/DraggableImage.vue')['default']
    ExifBrowser: typeof import('./src/components/ExifBrowser.vue')['default']
    FileItem: typeof import('./src/components/FileItem.vue')['default']
    HistoryRecord: typeof import('./src/components/HistoryRecord.vue')['default']
    KvPairEditor: typeof import('./src/components/KvPairEditor.vue')['default']
    MultiSelectKeep: typeof import('./src/components/MultiSelectKeep.vue')['default']
    NumInput: typeof import('./src/components/numInput.vue')['default']
    OrganizeJobsPanel: typeof import('./src/components/OrganizeJobsPanel.vue')['default']
    PromptEditorModal: typeof import('./src/components/PromptEditorModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartOrganizeConfigModal: typeof import('./src/components/SmartOrganizeConfigModal.vue')['default']
    TipsCarousel: typeof import('./src/components/TipsCarousel.vue')['default']
  }
}
